#!/bin/sh

opt="${1:-0}"

#vcc='/usr/bin/valac'
vcc='/opt/vala/bin/valac'

for program in bh3d newton nbody3d
do
	$vcc -X -O$opt -X -lm --pkg json-glib-1.0 ${program}.vala symplectic.vala utils.vala
done

