#!/bin/sh

opt="${1:-0}"

#valac='/usr/bin/valac'
valac='/opt/vala/bin/valac'

outfile='utils'
executables='bh3d nbody3d newton'

# cleanup
rm -f $outfile $executables

# compile vala files
valafiles="${outfile}.vala symplectic.vala"
for executable in $executables
do
	valafiles="$valafiles ${executable}.vala"
done
$valac -v -X -lm --pkg json-glib-1.0 $valafiles

# hard link executables
for executable in $executables
do
	ln $outfile $executable
done
rm -f $outfile

# admire our work
ls -lAh $executables

