#!/bin/sh

opt="${1:-fast}"

C='\033[0;36m'
NC='\033[0m' # No Color

valac="valac -v --save-temps -X -O$opt -X -lm"
valac --version
which valac

# cleanup executables
echo $C"Cleaning Up . . ."$NC
rm -f $outfile TestKdS KdS bh3dRk4 raytrace-commands kerr-image \
	Simulate GenParticle GenLight
echo ""

# compile vala test files
echo $C"Compiling Vala Tests . . ."$NC
$valac --pkg json-glib-1.0 \
	TestKdS.vala bh3dSymp.vala \
	symplectic.vala utils.vala
echo ""

# compile vala files
echo $C"Compiling Vala . . ."$NC
$valac --pkg json-glib-1.0 --pkg gsl \
	KdS.vala bh3dSymp.vala \
	nbody3d.vala newton.vala symplectic.vala \
	icgenParticle.vala icgenLight.vala utils.vala
echo ""

# compile raytracer
echo $C"Compiling Raytracer . . ."$NC
$valac --pkg json-glib-1.0 raytrace-commands.vala
gcc -o kerr-image kerr-image.c -O$opt -Wall -std=c99 -pedantic -Wextra -Wno-unused-result -lm
echo ""

# compile Fortran
echo $C"Compiling Fortran . . ."$NC
gfortran -Jobj/Release/ -Wall -O2 -fimplicit-none \
	-c KdS.f90 -o obj/Release/main.o
gfortran -static -o bin/Release/KerrDeSitter obj/Release/main.o -s  
echo ""

# strip executables
echo $C"Stripping Executables . . ."$NC
case $opt in
	fast)	strip KdS raytrace-commands kerr-image;;
esac

ln KdS Simulate
ln KdS GenParticle
ln KdS GenLight
rm -f KdS

# admire our work
ls -lAh --color TestKdS Simulate GenParticle GenLight \
		raytrace-commands kerr-image
echo ""
ls -lAh --color */Release
echo ""

# generate documentation
echo $C"Generating Documentation . . ."$NC
rm -rf doc
valadoc -o doc --pkg json-glib-1.0 --pkg gsl icgenParticle.vala icgenLight.vala KdS.vala symplectic.vala bh3dSymp.vala nbody3d.vala newton.vala utils.vala
echo ""

# test
echo $C"Running Tests . . ."$NC
./TestKdS >/dev/null && echo ${C}OK${NC}

