#!/bin/sh

opt="${1:-0}"

valac="valac -v --save-temps -X -O$opt -X -lm"
valac --version
which valac

executables='bh3d nbody3d newton'

# cleanup
rm -f $outfile $executables bh3d.rk4 raytrace-commands kerr-image icgen
echo ""

# compile vala files
for executable in $executables
do
	rm -f ${executable}.c
	$valac --pkg json-glib-1.0 $executable.vala symplectic.vala utils.vala
	echo ""
done

$valac --pkg json-glib-1.0 bh3d.rk4.vala utils.vala
echo ""

$valac --pkg json-glib-1.0 raytrace-commands.vala
echo ""

gcc -o kerr-image kerr-image.c -O$opt -Wall -std=c99 -pedantic -Wextra -Wno-unused-result -lm
echo ""

$valac -q -X -w --pkg json-glib-1.0 --pkg gsl icgen.vala utils.vala
echo ""

# strip executables
case $opt in
	fast)	strip $executables bh3d.rk4 raytrace-commands kerr-image icgen;;
esac

# admire our work
ls -lAh --color $executables bh3d.rk4 raytrace-commands kerr-image icgen

