#!/bin/sh

raytracer=${1:-'./kerr-image'}
raytracer="nice -n 10 $raytracer"

outputDir='RaytracingOutput'
[ ! -d $outputDir ] && mkdir $outputDir

tmp1="/tmp/$USER-raytracer-tmp-1"
tmp2="/tmp/$USER-raytracer-tmp-2"
tmp3="/tmp/$USER-raytracer-tmp-3"
tmp4="/tmp/$USER-raytracer-tmp-4"

GREY='\033[1;30m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
NC='\033[0m' # No Colour

assemble () {
    wait
    cat $tmp1 $tmp2 $tmp3 $tmp4 | convert - $filename
    echo "${GREEN}${1}${NC}"
}

n=0
while read line
do
    filename=$outputDir/$(printf "%04d.png" $n)
    if [ ! -f $filename ]
    then
        trap 'echo ""; echo -n "${CYAN}Finishing $filename . . . ${NC}"; assemble "Done!"; exit' INT
        { echo -n $line | $raytracer 360 480 >$tmp4 2>/dev/null; } &
        { echo -n $line | $raytracer 240 360 >$tmp3 2>/dev/null; } &
        { echo -n $line | $raytracer 120 240 >$tmp2 2>/dev/null; } &
        { echo -n $line | $raytracer 0 120 >$tmp1 2>/dev/null; } &
        assemble "Written   $filename"
        trap - INT
    else
        echo "${GREY}Skipping  $filename${NC}"
    fi
    n=$(expr $n + 1)
done

