#!/bin/sh

ic=${1:-'initial-conditions.json'}
timeStep=${2:-0.5}
timeCoord=${3:-'tau'}

C='\033[0;36m'
NC='\033[0m' # No Color

# Pretty-print the parameter file
jq . $ic

# Run the simulator
echo -n ${C}"Simulating with $ic . . . "
$exe <$ic >$data
echo "Done!"${NC}

# Plot errors
#./plotErrors.py $timeCoord 1 <$data &
./plotErrors.py $timeCoord $(echo $(jq .IC.duration $ic) / $(jq .IC.step $ic) / $(jq .IC.plotratio $ic) / 2000 | bc) <$data &

# Plot potentials
./plotPotential.py <$pot &

# Plot 3D graphics
./plotBH.py <$data $(jq .IC.M $ic) $(jq .IC.a $ic) $(jq .IC.L $ic) `jq .IC.mu $ic` &

