#!/bin/sh

program=${1:-'./bh3dRk4'}
timeCoord=${2:-'tau'}
timeStep=${3:-0.5}

C='\033[0;36m'
NC='\033[0m' # No Color

# Generate the parameter file
ic='initial-conditions.json'
pot='/tmp/potential'
params='{ "method": "dnewton", "rMin": 3.0, "rMax": 12.0, "thMin": 0.15, "spin": 1.0, "Lfac": 1.0 }'
if ! [ -f $ic ]
then
	echo "${C}Creating fresh initial conditions file${NC}"
	echo $params | ./icgenParticle >$ic 2>$pot
        echo $params | jq .
else
	echo "${C}Using existing initial conditions file${NC}"
fi
# Pretty-print the parameter file
jq . $ic

# Run the simulator
datafile='/tmp/data'
echo -n ${C}"Simulating with $program . . . "
case $program in
	*Rk4)	$program <$ic >$datafile;;
	*)	$program <$ic | ./finterp.py $timeCoord $timeStep >$datafile;;
esac
echo "Done!"${NC}

# Plot errors
#./plotErrors.py $timeCoord 1 <$datafile &
./plotErrors.py $timeCoord $(echo $(jq .duration $ic) / $(jq .step $ic) / $(jq .plotratio $ic) / 2000 | bc) <$datafile &

# Plot potentials
./plotPotential.py <$pot &

# Plot 3D graphics
./plotBH.py <$datafile $(jq .M $ic) $(jq .a $ic) &

