#!/bin/sh

bh3ds=${1:-'./bh3dRk4 ./bh3dSymp'}
nbodys=${2:-'./nbody3d'}

C='\033[0;36m'
NC='\033[0m' # No Color

ic='initial-conditions.json'
pot='/tmp/potential'

int='./finterp.py'

params='{ "method": "dnewton", "rMin": 3.0, "rMax": 12.0, "elevation": 63.0, "spin": 1.0, "Lfac": 1.0 }'
echo $params | jq .
echo $params | ./icgenParticle >$ic 2>$pot
jq . $ic
for app in $bh3ds
do
	echo ${C}$app${NC}
	$app <$ic | $int tau 0.5 | ./plotBH.py `jq .IC.M $ic` `jq .IC.a $ic` `jq .IC.L $ic` `jq .IC.mu $ic`
done

params='{ "method": "dnewton", "r": 12.0, "elevation": 90.0, "spin": 1.0, "Lfac": 1.0 }'
echo $params | jq .
echo $params | ./icgenParticle >$ic 2>$pot
jq . $ic
for app in $bh3ds
do
	echo ${C}$app${NC}
	$app <$ic | $int tau 0.5 | ./plotBH.py `jq .IC.M $ic` `jq .IC.a $ic` `jq .IC.L $ic` `jq .IC.mu $ic`
done

params='{ "r": 3, "spin": 1.0 }'
echo $params | jq .
echo $params | ./icgenLight >$ic 2>$pot
jq . $ic
for app in $bh3ds
do
	echo ${C}$app${NC}
	$app <$ic | $int tau 0.1 | ./plotBH.py `jq .IC.M $ic` `jq .IC.a $ic` `jq .IC.L $ic` `jq .IC.mu $ic`
done

params='{ "r": 2, "spin": 1.0 }'
echo $params | jq .
echo $params | ./icgenLight >$ic 2>$pot
jq . $ic
for app in $bh3ds
do
	echo ${C}$app${NC}
	$app <$ic | $int tau 0.1 | ./plotBH.py `jq .IC.M $ic` `jq .IC.a $ic` `jq .IC.L $ic` `jq .IC.mu $ic`
done

for app in $nbodys
do
	echo ${C}$app${NC}
	$app <ic/SolarSystem 2>/tmp/progress | ./plotNBody.py
done

params='{ "method": "dnewton", "r": 12.0, "elevation": 0.0, "spin": 1.0, "Lfac": 1.0 }'
echo $params | jq .
echo $params | ./icgenParticle >$ic 2>$pot
jq . $ic
echo ${C}"./newton"${NC}
./newton <$ic | ./plotBH.py `jq .IC.M $ic` `jq .IC.a $ic` `jq .IC.L $ic`

