#!/bin/sh

bh3ds=${1:-'./bh3d.rk4.py ./bh3d.rk4 ./bh3d.py ./bh3d'}
nbodys=${2:-'./nbody3d.py ./nbody3d'}

C='\033[0;36m'
NC='\033[0m' # No Color

ic='initial-conditions'

int='./finterp.py'

./genparam.py 3.0 12.0 0.15 1.0 1.0 >$ic 2>/tmp/potential
jq . $ic
for app in $bh3ds
do
	echo ${C}$app${NC}
	$app <$ic | $int tau 0.5 | ./plotBH.py `jq .M $ic` `jq .a $ic`
done

./genparam.py 12.0 0.0 1.0 1.0 >$ic 2>/tmp/potential
jq . $ic
for app in $bh3ds
do
	echo ${C}$app${NC}
	$app <$ic | $int tau 1.0 | ./plotBH.py `jq .M $ic` `jq .a $ic`
done

jq . ic/Light1
for app in $bh3ds
do
	echo ${C}$app${NC}
	$app <ic/Light1 | $int t 0.5 | ./plotBH.py `jq .M ic/Light1` `jq .a ic/Light1`
done

for app in $nbodys
do
	echo ${C}$app${NC}
	$app <ic/SolarSystem 2>/tmp/progress | ./plotNBody.py
done

./genparam.py 12.0 0.5 1.0 1.0 >$ic 2>/tmp/potential
jq . $ic
echo ${C}"./newton"${NC}
./newton <$ic | $int t 0.1 | ./plotBH.py `jq .M $ic` `jq .a $ic`

