#!/bin/sh

ic=$1
points=${2:-2000}

d='/tmp/data'

./bh3d.py <$ic >$d &
PID=$!
sleep 1
./filegraphics.py $d $ic $points &
wait $PID
./filepotential.py potential &
#./interpolate.py $d $points 't' &
#./interpolate.py $d $points 'r' &
#./interpolate.py $d $points 'th' &
#./interpolate.py $d $points 'ph' &
./errorchart.py $d $points &

