#!/bin/sh

initialConditions=$1
time=$2
nPoints=$3
shift 3
coordinates=$*

dataFile='/tmp/data'

# run simulator
./bh3dy <$initialConditions >$dataFile

# plot orbit
./filegraphics.py $dataFile $initialConditions $time $nPoints &

# plot potential, coordinates/velocities (optional) and errors
./filepotential.py potential &
for coordinate in $coordinates
do
	./phase.py $dataFile $time $nPoints $coordinate &
	./interpolate.py $dataFile $time $nPoints $coordinate &
done
./errorchart.py $dataFile $time $nPoints &

